server:
  port: 8899

spring:
  application:
    name: spring-ai-function-demo
  ai:
    openai:
      api-key: ${SPRINGAI_LEARNING_DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7